### ISSUE TITLE
Friends do not load - TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by RealExoctic** [RealSimplyData/blox-plus#2]
Friends do not load, and opening the Dev Console shows these 2 errors:
```
Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at y.fetchFriends (app.89241e36.js:1)
```
```
Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at y.fetchFriends (app.89241e36.js:1)
```

**Comment by RealSimplyData** [comment]
I'm aware of this issue, but I'm missing information as to why this is happening.
Could you do the following:
- Check how many friends you have
- Is there at least 1 banned person your friend

**Comment by RealExoctic** [comment]
1. 135
2. I don't have any banned friends

**Comment by RealSimplyData** [comment]
This should be fixed with https://github.com/RealSimplyData/blox-plus/pull/4/commits/fde13dc69a91e074f8cbf13e54a9b2f529bdb8d8 hopefully.
